// Monde initial (phase 1). Données de démonstration volontairement génériques (Item N, Manager N…) :
// le thème et les « vrais » noms viendront plus tard. Structure reprise de docs/reference/origworld.skeleton.ts.
// Ne jamais muter cet objet : le servir via structuredClone(origworld) (voir docs/DECISIONS.md, D3).
import { RatioType, World } from './graphql.js';

export const origworld: World = {
  name: 'World',
  logo: 'icones/world.png',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Item 1',
      logo: 'icones/item1.png',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 1.1',
          logo: 'icones/item1.png',
          seuil: 25,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 1.2',
          logo: 'icones/item1.png',
          seuil: 50,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 1.3',
          logo: 'icones/item1.png',
          seuil: 100,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Item 2',
      logo: 'icones/item2.png',
      cout: 60,
      croissance: 1.15,
      revenu: 60,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 2.1',
          logo: 'icones/item2.png',
          seuil: 25,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 2.2',
          logo: 'icones/item2.png',
          seuil: 50,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 2.3',
          logo: 'icones/item2.png',
          seuil: 100,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Item 3',
      logo: 'icones/item3.png',
      cout: 720,
      croissance: 1.14,
      revenu: 540,
      vitesse: 6000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 3.1',
          logo: 'icones/item3.png',
          seuil: 25,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 3.2',
          logo: 'icones/item3.png',
          seuil: 50,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 3.3',
          logo: 'icones/item3.png',
          seuil: 100,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 4,
      name: 'Item 4',
      logo: 'icones/item4.png',
      cout: 8640,
      croissance: 1.13,
      revenu: 4320,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 4.1',
          logo: 'icones/item4.png',
          seuil: 25,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 4.2',
          logo: 'icones/item4.png',
          seuil: 50,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 4.3',
          logo: 'icones/item4.png',
          seuil: 100,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 5,
      name: 'Item 5',
      logo: 'icones/item5.png',
      cout: 103680,
      croissance: 1.12,
      revenu: 51840,
      vitesse: 48000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 5.1',
          logo: 'icones/item5.png',
          seuil: 25,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 5.2',
          logo: 'icones/item5.png',
          seuil: 50,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 5.3',
          logo: 'icones/item5.png',
          seuil: 100,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 6,
      name: 'Item 6',
      logo: 'icones/item6.png',
      cout: 1244160,
      croissance: 1.11,
      revenu: 622080,
      vitesse: 120000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Unlock 6.1',
          logo: 'icones/item6.png',
          seuil: 25,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Unlock 6.2',
          logo: 'icones/item6.png',
          seuil: 50,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unlock 6.3',
          logo: 'icones/item6.png',
          seuil: 100,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
  ],
  // Seuil = quantité que TOUS les produits doivent atteindre.
  allunlocks: [
    {
      name: 'All Unlock 1',
      logo: 'icones/all.png',
      seuil: 25,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'All Unlock 2',
      logo: 'icones/all.png',
      seuil: 50,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'All Unlock 3',
      logo: 'icones/all.png',
      seuil: 100,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.vitesse,
      unlocked: false,
    },
  ],
  // Seuil = prix en argent.
  upgrades: [
    {
      name: 'Upgrade 1',
      logo: 'icones/item1.png',
      seuil: 1000,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 2',
      logo: 'icones/item2.png',
      seuil: 15000,
      idcible: 2,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 3',
      logo: 'icones/item3.png',
      seuil: 180000,
      idcible: 3,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 4',
      logo: 'icones/item4.png',
      seuil: 2160000,
      idcible: 4,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 5',
      logo: 'icones/item5.png',
      seuil: 26000000,
      idcible: 5,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 6',
      logo: 'icones/item6.png',
      seuil: 310000000,
      idcible: 6,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 7',
      logo: 'icones/all.png',
      seuil: 1e6,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 8',
      logo: 'icones/all.png',
      seuil: 1e8,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 9',
      logo: 'icones/all.png',
      seuil: 1e10,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Upgrade 10',
      logo: 'icones/all.png',
      seuil: 1e12,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  // Seuil = prix en anges actifs.
  angelupgrades: [
    {
      name: 'Angel Upgrade 1',
      logo: 'icones/angel.png',
      seuil: 10,
      idcible: -1,
      ratio: 1,
      typeratio: RatioType.ange,
      unlocked: false,
    },
    {
      name: 'Angel Upgrade 2',
      logo: 'icones/angel.png',
      seuil: 100,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Angel Upgrade 3',
      logo: 'icones/angel.png',
      seuil: 1000,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
  ],
  // Seuil = prix en argent. ratio/typeratio sont décoratifs : engagerManager n'applique aucun bonus (D13).
  managers: [
    {
      name: 'Manager 1',
      logo: 'icones/manager1.png',
      seuil: 1000,
      idcible: 1,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Manager 2',
      logo: 'icones/manager2.png',
      seuil: 15000,
      idcible: 2,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Manager 3',
      logo: 'icones/manager3.png',
      seuil: 100000,
      idcible: 3,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Manager 4',
      logo: 'icones/manager4.png',
      seuil: 500000,
      idcible: 4,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Manager 5',
      logo: 'icones/manager5.png',
      seuil: 1200000,
      idcible: 5,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Manager 6',
      logo: 'icones/manager6.png',
      seuil: 10000000,
      idcible: 6,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};
