// Monde initial « Nuka Capitalist » (thème Fallout, docs/THEME.md ; casting appliqué en phase 10.4).
// Chiffres d'origine (phase 1, calqués sur le monde « Terre » d'AdVenture Capitalist), noms et images
// du casting. Structure reprise de docs/reference/origworld.skeleton.ts.
// Ne jamais muter cet objet : le servir via structuredClone(origworld) (voir docs/DECISIONS.md, D3).
import { RatioType, World } from './graphql.js';

export const origworld: World = {
  name: 'Nuka Capitalist',
  logo: 'icones/world.png',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Nuka-Cola',
      logo: 'icones/nuka-cola.png',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Nuka-Cherry',
          logo: 'icones/nuka-cola.png',
          seuil: 25,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Nuka-Cola Quantum',
          logo: 'icones/nuka-cola.png',
          seuil: 50,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Nuka-Cola Victory',
          logo: 'icones/nuka-cola.png',
          seuil: 100,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Stimpak',
      logo: 'icones/stimpak.png',
      cout: 60,
      croissance: 1.15,
      revenu: 60,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Med-X',
          logo: 'icones/stimpak.png',
          seuil: 25,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'RadAway',
          logo: 'icones/stimpak.png',
          seuil: 50,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Super Stimpak',
          logo: 'icones/stimpak.png',
          seuil: 100,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Pip-Boy',
      logo: 'icones/pip-boy.png',
      cout: 720,
      croissance: 1.14,
      revenu: 540,
      vitesse: 6000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Pip-Boy 2000',
          logo: 'icones/pip-boy.png',
          seuil: 25,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Pip-Boy 3000',
          logo: 'icones/pip-boy.png',
          seuil: 50,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Pip-Boy 3000 Mark IV',
          logo: 'icones/pip-boy.png',
          seuil: 100,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 4,
      name: 'Armes',
      logo: 'icones/armes.png',
      cout: 8640,
      croissance: 1.13,
      revenu: 4320,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Fusil laser AER9',
          logo: 'icones/armes.png',
          seuil: 25,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Fusil à plasma',
          logo: 'icones/armes.png',
          seuil: 50,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Fusil Gauss',
          logo: 'icones/armes.png',
          seuil: 100,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 5,
      name: 'Armure assistée',
      logo: 'icones/armure.png',
      cout: 103680,
      croissance: 1.12,
      revenu: 51840,
      vitesse: 48000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'T-45',
          logo: 'icones/armure.png',
          seuil: 25,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'T-51',
          logo: 'icones/armure.png',
          seuil: 50,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'X-01',
          logo: 'icones/armure.png',
          seuil: 100,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 6,
      name: 'Nuke',
      logo: 'icones/nuke.png',
      cout: 1244160,
      croissance: 1.11,
      revenu: 622080,
      vitesse: 120000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Fat Man',
          logo: 'icones/nuke.png',
          seuil: 25,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Ogive MIRV expérimentale',
          logo: 'icones/nuke.png',
          seuil: 50,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Missile nucléaire (Site Alpha)',
          logo: 'icones/nuke.png',
          seuil: 100,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
  ],
  // Seuil = quantité que TOUS les produits doivent atteindre.
  allunlocks: [
    {
      name: 'Sanctuary',
      logo: 'icones/global.png',
      seuil: 25,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Diamond City',
      logo: 'icones/global.png',
      seuil: 50,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Nuka-World',
      logo: 'icones/global.png',
      seuil: 100,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.vitesse,
      unlocked: false,
    },
  ],
  // Seuil = prix en argent.
  upgrades: [
    {
      name: 'Bottle',
      logo: 'icones/upgrade-bottle.png',
      seuil: 1000,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Doc Phosphate',
      logo: 'icones/stimpak.png',
      seuil: 15000,
      idcible: 2,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Vault Girl',
      logo: 'icones/upgrade-vault-girl.png',
      seuil: 180000,
      idcible: 3,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'One-Eyed Ike',
      logo: 'icones/armes.png',
      seuil: 2160000,
      idcible: 4,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'The Mechanist',
      logo: 'icones/armure.png',
      seuil: 26000000,
      idcible: 5,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Sugar Bombs',
      logo: 'icones/upgrade-sugar-bombs.png',
      seuil: 310000000,
      idcible: 6,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Tales of a Junktown Jerky Vendor',
      logo: 'icones/global.png',
      seuil: 1e6,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Grognak the Barbarian',
      logo: 'icones/global.png',
      seuil: 1e8,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Guns and Bullets',
      logo: 'icones/global.png',
      seuil: 1e10,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Astoundingly Awesome Tales',
      logo: 'icones/global.png',
      seuil: 1e12,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  // Seuil = prix en anges actifs.
  angelupgrades: [
    {
      name: 'Fortune Finder',
      logo: 'icones/bobblehead.png',
      seuil: 10,
      idcible: -1,
      ratio: 1,
      typeratio: RatioType.ange,
      unlocked: false,
    },
    {
      name: 'Cap Collector',
      logo: 'icones/bobblehead.png',
      seuil: 100,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Troc',
      logo: 'icones/bobblehead.png',
      seuil: 1000,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
  ],
  // Seuil = prix en argent. ratio/typeratio sont décoratifs : engagerManager n'applique aucun bonus (D13).
  managers: [
    {
      name: 'Cappy',
      logo: 'icones/manager-cappy.png',
      seuil: 1000,
      idcible: 1,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Mister Orderly',
      logo: 'icones/manager-mister-orderly.png',
      seuil: 15000,
      idcible: 2,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Vault Boy',
      logo: 'icones/manager-vault-boy-pipboy.png',
      seuil: 100000,
      idcible: 3,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Gunslinger',
      logo: 'icones/manager-vault-boy-gunslinger.png',
      seuil: 500000,
      idcible: 4,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: "Confrérie de l'Acier",
      logo: 'icones/manager-confrerie.png',
      seuil: 1200000,
      idcible: 5,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Nuka-Girl',
      logo: 'icones/manager-nuka-girl.png',
      seuil: 10000000,
      idcible: 6,
      ratio: 1,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};
